INSERT INTO public.address (country, city, street, house_number) VALUES ('Czech Republic','Brno', 'Žítná', '23');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Czech Republic','Brno', 'Herčíkova', '2494');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Czech Republic','Brno', 'Obilní trh', '10');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Czech Republic','Praha', 'Na Hřebenech', '51');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Czech Republic','Pardubice', 'Ke Koupališti', '66');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Torino', 'Corso Gaetano Scirea', '50');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Milano', 'Piazzale Angelo Moratti', '2');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Bergamo', 'Viale Giulio Cesare', '18');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Roma', 'Viale dei Gladiatori', '2');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Roma', 'Viale dei Gladiatori', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Milano', 'Piazzale Angelo Moratti', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Napoli', 'Piazzale Vincenzo Tecchio', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Reggio Emilia', 'Piazzale Atleti Azzuri DItalia', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Verona', 'Piazzale Olimpia', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Firenze', 'Viale Manfredo Fanti', '4');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Parma', 'Viale Partigiani DItalia', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Bologna', 'Via Casteldebole', '10');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Udine', 'Piazzale Repubblica Argentina', '3');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Cagliari', 'Via Raimondo Carta Raspi', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Genova', 'Via Giovanni', '2');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Torino', 'Via Filadelfia', '96');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Genova', 'Via Giovanni de Prà', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Lecce', 'Viale Stadio', '1');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Brescia', 'Via Giovanni Novagani', '9');
INSERT INTO public.address (country, city, street, house_number) VALUES ('Italy','Ferrara', 'Corso Piave', '28');