-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 20:38:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bds-db-design
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bds-db-design
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bds-db-design` DEFAULT CHARACTER SET utf8 ;
USE `bds-db-design` ;

-- -----------------------------------------------------
-- Table `bds-db-design`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`user` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `sirname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`round_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`round_schedule` (
  `round_schedule_id` INT NOT NULL,
  `round_number` INT NOT NULL,
  PRIMARY KEY (`round_schedule_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`round_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`round_stats` (
  `round_stats_id` INT NOT NULL,
  `total_number_of_goals` INT NOT NULL,
  `max_goals_in_a_match` INT NOT NULL,
  `total_number_of_assists` INT NOT NULL,
  `round_schedule` INT NOT NULL,
  PRIMARY KEY (`round_stats_id`, `round_schedule`),
  INDEX `fk_round_stats_round_schedule1_idx` (`round_schedule` ASC)  ,
  CONSTRAINT `fk_round_stats_round_schedule1`
    FOREIGN KEY (`round_schedule`)
    REFERENCES `bds-db-design`.`round_schedule` (`round_schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`user_round_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`user_round_points` (
  `user_round_points_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `users_total_number_of_goals` INT NOT NULL,
  `user_max_goals_in_a_match` INT NOT NULL,
  `users_total_number_of_assist` VARCHAR(45) NOT NULL,
  `round_stats_id` INT NOT NULL,
  PRIMARY KEY (`user_round_points_id`, `user_id`, `round_stats_id`),
  INDEX `fk_user_round_points_round_stats1_idx` (`round_stats_id` ASC)  ,
  CONSTRAINT `fk_table1_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bds-db-design`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_round_points_round_stats1`
    FOREIGN KEY (`round_stats_id`)
    REFERENCES `bds-db-design`.`round_stats` (`round_stats_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`football_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`football_team` (
  `football_team_id` INT NOT NULL,
  `team_name` VARCHAR(45) NOT NULL,
  `number_of_trophy` INT NULL,
  PRIMARY KEY (`football_team_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`address` (
  `address_id` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`team_stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`team_stadium` (
  `team_stadium_id` INT NOT NULL,
  `stadium_name` VARCHAR(45) NOT NULL,
  `match_date` DATETIME NULL,
  `football_team_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`team_stadium_id`, `football_team_id`, `address_id`),
  INDEX `fk_team_stadium_football_team1_idx` (`football_team_id` ASC)  ,
  INDEX `fk_team_stadium_address1_idx` (`address_id` ASC)  ,
  CONSTRAINT `fk_team_stadium_football_team1`
    FOREIGN KEY (`football_team_id`)
    REFERENCES `bds-db-design`.`football_team` (`football_team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_stadium_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `bds-db-design`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`team_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`team_game` (
  `game_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `football_team1_id` INT NOT NULL,
  `football_team2_id` INT NOT NULL,
  `round_schedule_id` INT NOT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `fk_team_game_football_team1_idx` (`football_team1_id` ASC)  ,
  INDEX `fk_team_game_football_team2_idx` (`football_team2_id` ASC)  ,
  INDEX `fk_team_game_round_schedule1_idx` (`round_schedule_id` ASC)  ,
  CONSTRAINT `fk_team_game_football_team1`
    FOREIGN KEY (`football_team1_id`)
    REFERENCES `bds-db-design`.`football_team` (`football_team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_game_football_team2`
    FOREIGN KEY (`football_team2_id`)
    REFERENCES `bds-db-design`.`football_team` (`football_team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_game_round_schedule1`
    FOREIGN KEY (`round_schedule_id`)
    REFERENCES `bds-db-design`.`round_schedule` (`round_schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`user_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`user_has_address` (
  `user_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `address_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `address_id`),
  INDEX `fk_user_has_address_address1_idx` (`address_id` ASC)  ,
  INDEX `fk_user_has_address_user1_idx` (`user_id` ASC)  ,
  CONSTRAINT `fk_user_has_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bds-db-design`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_address_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `bds-db-design`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`manager` (
  `manager_id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `sirname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`manager_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`player` (
  `player_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `contract` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `manager_id` INT NOT NULL,
  `football_team_id` INT NOT NULL,
  PRIMARY KEY (`player_id`, `manager_id`, `football_team_id`),
  INDEX `fk_player_manager1_idx` (`manager_id` ASC)  ,
  INDEX `fk_player_football_team1_idx` (`football_team_id` ASC)  ,
  CONSTRAINT `fk_player_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `bds-db-design`.`manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_football_team1`
    FOREIGN KEY (`football_team_id`)
    REFERENCES `bds-db-design`.`football_team` (`football_team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bds-db-design`.`trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bds-db-design`.`trainer` (
  `trainer_id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `sirname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `manager_id` INT NOT NULL,
  `football_team_id` INT NOT NULL,
  PRIMARY KEY (`trainer_id`, `manager_id`, `football_team_id`),
  INDEX `fk_trainer_manager1_idx` (`manager_id` ASC)  ,
  INDEX `fk_trainer_football_team1_idx` (`football_team_id` ASC)  ,
  CONSTRAINT `fk_trainer_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `bds-db-design`.`manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainer_football_team1`
    FOREIGN KEY (`football_team_id`)
    REFERENCES `bds-db-design`.`football_team` (`football_team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
