INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Juventus', '87');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Internazionale Milano', '40');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Atalanta', '9');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Lázio', '18');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Roma', '17');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Milan', '71');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Napoli', '16');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Sassuolo', '2');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Hellas Verona', '4');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Fiorentina', '16');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Parma', '14');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Bologna ', '16');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Udinese', '10');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Cagliari ', '2');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Sampdoria', '15');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Torino', '13');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Genoa', '21');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Lecce', null);
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('Brescia', '2');
INSERT INTO public.football_team (team_name, number_of_trophy) VALUES ('SPAL ', '1');