INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Allianz Stadium','2021-10-30','1','6');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Giuseppe Meazza','2021-10-31','2','7');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Gewiss Stadium','2021-10-30','3','8');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Olimpico','2021-10-30','4','9');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Olimpico','2021-10-31','5','10');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('San Siro','2021-10-31','6','11');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Diego Armando Maradona','2021-10-31','7','12');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Mapei Stadium','2021-10-31','8','13');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Contenuto non trovato','2021-10-30','9','14');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Artemio Franchi','2021-10-31','10','15');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Ennio Tardini','2021-11-01','11','16');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Renato DallAra','2021-11-01','12','17');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Friuli','2021-10-31','13','18');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Sardegna Arena','2021-11-01','14','19');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Comunale Luigi Ferraris','2021-10-30','15','20');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Grande Torino','2021-10-30','16','21');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Luigi Ferraris','2021-10-31','17','22');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Via del Mare','2021-11-01','18','23');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Mario Rigamonti','2021-11-01','19','24');
INSERT INTO public.team_stadium (stadium_name, match_date, football_team_id, address_id) VALUES ('Stadio Paolo Mazza','2021-11-01','20','25');